import { useWorkflowDiagram } from '@/api/task'
import { Loader2, GitBranch } from 'lucide-react'
import type { WorkflowState, ProgressPhase } from '@/types/api'
import { getStateConfigWithProgress } from '@/constants/stateConfig'

interface WorkflowDiagramProps {
  currentState?: WorkflowState
  progressPhase?: ProgressPhase
}

export function WorkflowDiagram({ currentState, progressPhase }: WorkflowDiagramProps) {
  const { data: svgContent, isLoading, error } = useWorkflowDiagram()

  if (isLoading) {
    return (
      <div className="card bg-base-100 shadow-sm">
        <div className="card-body py-4">
          <div className="flex items-center gap-2 text-sm font-medium text-base-content/80">
            <GitBranch size={16} />
            Workflow
          </div>
          <div className="flex items-center justify-center py-8">
            <Loader2 className="w-6 h-6 animate-spin text-primary" />
          </div>
        </div>
      </div>
    )
  }

  if (error || !svgContent) {
    return (
      <div className="card bg-base-100 shadow-sm">
        <div className="card-body py-4">
          <div className="flex items-center gap-2 text-sm font-medium text-base-content/80">
            <GitBranch size={16} />
            Workflow
          </div>
          <p className="text-sm text-base-content/50 text-center py-4">
            Unable to load workflow diagram
          </p>
        </div>
      </div>
    )
  }

  // Process SVG to highlight current state (or progress-derived state when idle)
  const stateToHighlight = getDiagramHighlightState(currentState, progressPhase)
  const processedSvg = stateToHighlight ? highlightCurrentState(svgContent, stateToHighlight) : svgContent

  // Compute progress-aware display (e.g., "Planned" instead of "idle")
  const stateDisplay = currentState
    ? getStateConfigWithProgress(currentState, progressPhase)
    : null

  return (
    <div className="card bg-base-100 shadow-sm">
      <div className="card-body py-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 text-sm font-medium text-base-content/80">
            <GitBranch size={16} />
            Workflow
          </div>
          {stateDisplay && <span className={`badge badge-sm ${stateDisplay.badge}`}>{stateDisplay.displayState}</span>}
        </div>
        {/* SVG from internal Go backend - trusted content, not user input */}
        <div
          className="workflow-diagram mt-2 overflow-x-auto [&_svg]:max-w-full [&_svg]:h-auto"
          dangerouslySetInnerHTML={{ __html: processedSvg }}
        />
      </div>
    </div>
  )
}

function getDiagramHighlightState(
  currentState?: WorkflowState,
  progressPhase?: ProgressPhase
): WorkflowState | undefined {
  if (!currentState) {
    return undefined
  }

  // Idle may represent completed progress between active runs.
  // Highlight the most relevant phase so the diagram matches the visible badge/context.
  if (currentState === 'idle') {
    switch (progressPhase) {
      case 'planned':
        return 'planning'
      case 'implemented':
        return 'implementing'
      case 'reviewed':
        return 'reviewing'
      default:
        return 'idle'
    }
  }

  return currentState
}

/**
 * Highlight the current state in the SVG diagram.
 * Adds CSS styling to nodes matching the current state name.
 */
function highlightCurrentState(svg: string, state: WorkflowState): string {
  const parser = new DOMParser()
  const doc = parser.parseFromString(svg, 'image/svg+xml')
  const root = doc.documentElement

  if (!root || root.tagName.toLowerCase() !== 'svg') {
    return svg
  }

  // Remove existing backend "current" class so UI state is authoritative.
  const stateBoxes = doc.querySelectorAll('rect.state-box')
  stateBoxes.forEach((box) => {
    box.classList.remove('current', 'workflow-current')
  })

  // Match node by text label generated by backend (idle/planning/implementing/etc).
  const targetLabel = state.toLowerCase()
  const labels = doc.querySelectorAll('text.state-text')
  labels.forEach((label) => {
    if (label.textContent?.trim().toLowerCase() !== targetLabel) {
      return
    }

    const previous = label.previousElementSibling
    if (previous && previous.tagName.toLowerCase() === 'rect' && previous.classList.contains('state-box')) {
      previous.classList.add('workflow-current')
    }
  })

  const style = doc.createElementNS('http://www.w3.org/2000/svg', 'style')
  style.textContent = `
    .state-box.workflow-current {
      fill: oklch(var(--p)) !important;
      stroke: oklch(var(--pf)) !important;
      stroke-width: 2px;
    }
    .state-box.workflow-current + .state-text {
      fill: oklch(var(--pc)) !important;
      font-weight: bold;
    }
  `
  root.insertBefore(style, root.firstChild)

  return new XMLSerializer().serializeToString(doc)
}
