package backup

import (
	"archive/tar"
	"compress/gzip"
	"errors"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestIsTransientFile(t *testing.T) {
	tests := []struct {
		name string
		want bool
	}{
		{"global.sock", true},
		{"worktree.sock", true},
		{"db.lock", true},
		{"main.go", false},
		{"config.yaml", false},
		{"backup.tar.gz", false},
		{"readme.md", false},
		{".sock", true},
		{".lock", true},
		{"path/to/file.sock", true},
		{"path/to/file.lock", true},
		{"path/to/file.go", false},
	}

	for _, tt := range tests {
		got := IsTransientFile(tt.name)
		if got != tt.want {
			t.Errorf("IsTransientFile(%q) = %v, want %v", tt.name, got, tt.want)
		}
	}
}

func TestFormatBytes(t *testing.T) {
	tests := []struct {
		input int64
		want  string
	}{
		{0, "0 B"},
		{1, "1 B"},
		{512, "512 B"},
		{1023, "1023 B"},
		{1024, "1.0 KiB"},
		{1536, "1.5 KiB"},
		{1048576, "1.0 MiB"},
		{1073741824, "1.0 GiB"},
		{1099511627776, "1.0 TiB"},
	}

	for _, tt := range tests {
		got := FormatBytes(tt.input)
		if got != tt.want {
			t.Errorf("FormatBytes(%d) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

func TestCreateBasicBackup(t *testing.T) {
	// Create a temp directory with some files to back up
	srcDir := t.TempDir()

	files := map[string]string{
		"config.yaml": "key: value",
		"data.json":   `{"hello": "world"}`,
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(srcDir, name), []byte(content), 0o644); err != nil {
			t.Fatalf("Failed to create test file %s: %v", name, err)
		}
	}

	// Create backup with explicit output path
	outDir := t.TempDir()
	outPath := filepath.Join(outDir, "test-backup.tar.gz")

	result, err := Create(srcDir, outPath)
	if err != nil {
		t.Fatalf("Create() failed: %v", err)
	}

	if result.Files != len(files) {
		t.Errorf("Result.Files = %d, want %d", result.Files, len(files))
	}
	if result.Size <= 0 {
		t.Errorf("Result.Size = %d, want > 0", result.Size)
	}
	if result.Path != outPath {
		t.Errorf("Result.Path = %q, want %q", result.Path, outPath)
	}

	// Verify the archive contents
	verifyArchiveContents(t, outPath, files)
}

func TestCreateAutoGeneratedFilename(t *testing.T) {
	srcDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(srcDir, "file.txt"), []byte("hello"), 0o644); err != nil {
		t.Fatalf("Failed to create test file: %v", err)
	}

	// Use a temp dir as working directory so the auto-generated file lands there
	outDir := t.TempDir()
	t.Chdir(outDir)

	result, err := Create(srcDir, "")
	if err != nil {
		t.Fatalf("Create() with empty outputPath failed: %v", err)
	}

	if !strings.HasPrefix(filepath.Base(result.Path), "kvelmo-backup-") {
		t.Errorf("Auto-generated filename %q does not start with kvelmo-backup-", filepath.Base(result.Path))
	}
	if !strings.HasSuffix(result.Path, ".tar.gz") {
		t.Errorf("Auto-generated filename %q does not end with .tar.gz", result.Path)
	}

	t.Cleanup(func() { _ = os.Remove(result.Path) })
}

func TestCreateNonexistentDirectory(t *testing.T) {
	_, err := Create("/nonexistent/path/that/does/not/exist", "")
	if err == nil {
		t.Fatal("Create() with nonexistent directory should return an error")
	}
	if !strings.Contains(err.Error(), "does not exist") {
		t.Errorf("Error message %q should contain 'does not exist'", err.Error())
	}
}

func TestCreateSkipsTransientFiles(t *testing.T) {
	srcDir := t.TempDir()

	// Create a regular file and transient files
	if err := os.WriteFile(filepath.Join(srcDir, "config.yaml"), []byte("data"), 0o644); err != nil {
		t.Fatalf("Failed to create config.yaml: %v", err)
	}
	if err := os.WriteFile(filepath.Join(srcDir, "server.sock"), []byte(""), 0o644); err != nil {
		t.Fatalf("Failed to create server.sock: %v", err)
	}
	if err := os.WriteFile(filepath.Join(srcDir, "db.lock"), []byte(""), 0o644); err != nil {
		t.Fatalf("Failed to create db.lock: %v", err)
	}

	outDir := t.TempDir()
	outPath := filepath.Join(outDir, "backup.tar.gz")

	result, err := Create(srcDir, outPath)
	if err != nil {
		t.Fatalf("Create() failed: %v", err)
	}

	// Only the config.yaml should be in the archive (not .sock or .lock)
	if result.Files != 1 {
		t.Errorf("Result.Files = %d, want 1 (transient files should be skipped)", result.Files)
	}

	// Verify archive does not contain transient files
	names := listArchiveEntries(t, outPath)
	for _, name := range names {
		if strings.HasSuffix(name, ".sock") || strings.HasSuffix(name, ".lock") {
			t.Errorf("Archive contains transient file: %s", name)
		}
	}
}

func TestCreateWithSubdirectories(t *testing.T) {
	srcDir := t.TempDir()

	subDir := filepath.Join(srcDir, "subdir")
	if err := os.MkdirAll(subDir, 0o755); err != nil {
		t.Fatalf("Failed to create subdir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(srcDir, "root.txt"), []byte("root"), 0o644); err != nil {
		t.Fatalf("Failed to create root.txt: %v", err)
	}
	if err := os.WriteFile(filepath.Join(subDir, "nested.txt"), []byte("nested"), 0o644); err != nil {
		t.Fatalf("Failed to create nested.txt: %v", err)
	}

	outDir := t.TempDir()
	outPath := filepath.Join(outDir, "backup.tar.gz")

	result, err := Create(srcDir, outPath)
	if err != nil {
		t.Fatalf("Create() failed: %v", err)
	}

	// 2 regular files (directories are not counted in fileCount)
	if result.Files != 2 {
		t.Errorf("Result.Files = %d, want 2", result.Files)
	}
}

func TestListBackups(t *testing.T) {
	dir := t.TempDir()

	// Create backup files with correct naming pattern
	backupFiles := []string{
		"kvelmo-backup-20260101-120000.tar.gz",
		"kvelmo-backup-20260102-120000.tar.gz",
	}
	for _, name := range backupFiles {
		if err := os.WriteFile(filepath.Join(dir, name), []byte("fake"), 0o644); err != nil {
			t.Fatalf("Failed to create %s: %v", name, err)
		}
	}

	// Create files that should NOT match
	nonBackupFiles := []string{
		"other-file.tar.gz",
		"kvelmo-backup-incomplete",
		"kvelmo-backup-.txt",
		"random.txt",
	}
	for _, name := range nonBackupFiles {
		if err := os.WriteFile(filepath.Join(dir, name), []byte("ignore"), 0o644); err != nil {
			t.Fatalf("Failed to create %s: %v", name, err)
		}
	}

	// Create a subdirectory with backup-like name (should be skipped)
	if err := os.MkdirAll(filepath.Join(dir, "kvelmo-backup-dir.tar.gz"), 0o755); err != nil {
		t.Fatalf("Failed to create dir: %v", err)
	}

	backups, err := List(dir)
	if err != nil {
		t.Fatalf("List() failed: %v", err)
	}

	if len(backups) != len(backupFiles) {
		t.Fatalf("List() returned %d backups, want %d", len(backups), len(backupFiles))
	}

	for _, b := range backups {
		if !strings.HasPrefix(b.Name, "kvelmo-backup-") {
			t.Errorf("Backup name %q does not have expected prefix", b.Name)
		}
		if b.Size <= 0 {
			t.Errorf("Backup %q has size %d, want > 0", b.Name, b.Size)
		}
		if b.CreatedAt == "" {
			t.Errorf("Backup %q has empty CreatedAt", b.Name)
		}
		if b.Path == "" {
			t.Errorf("Backup %q has empty Path", b.Name)
		}
	}
}

func TestListNonexistentDirectory(t *testing.T) {
	backups, err := List("/nonexistent/dir/path")
	if err != nil {
		t.Fatalf("List() with nonexistent dir should return nil error, got: %v", err)
	}
	if backups != nil {
		t.Errorf("List() with nonexistent dir should return nil, got %v", backups)
	}
}

func TestListEmptyDirectory(t *testing.T) {
	dir := t.TempDir()

	backups, err := List(dir)
	if err != nil {
		t.Fatalf("List() failed: %v", err)
	}
	if len(backups) != 0 {
		t.Errorf("List() on empty dir returned %d backups, want 0", len(backups))
	}
}

// verifyArchiveContents checks that the tar.gz archive contains the expected files with correct content.
func verifyArchiveContents(t *testing.T, archivePath string, expected map[string]string) {
	t.Helper()

	f, err := os.Open(archivePath)
	if err != nil {
		t.Fatalf("Failed to open archive: %v", err)
	}
	defer func() { _ = f.Close() }()

	gz, err := gzip.NewReader(f)
	if err != nil {
		t.Fatalf("Failed to create gzip reader: %v", err)
	}
	defer func() { _ = gz.Close() }()

	tr := tar.NewReader(gz)
	found := make(map[string]string)

	for {
		header, err := tr.Next()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			t.Fatalf("Failed to read tar entry: %v", err)
		}

		if header.Typeflag == tar.TypeDir {
			continue
		}

		data, err := io.ReadAll(tr)
		if err != nil {
			t.Fatalf("Failed to read tar entry content: %v", err)
		}
		found[header.Name] = string(data)
	}

	for name, wantContent := range expected {
		gotContent, ok := found[name]
		if !ok {
			t.Errorf("Expected file %q not found in archive", name)

			continue
		}
		if gotContent != wantContent {
			t.Errorf("File %q content = %q, want %q", name, gotContent, wantContent)
		}
	}
}

// listArchiveEntries returns the names of all entries in a tar.gz archive.
func listArchiveEntries(t *testing.T, archivePath string) []string {
	t.Helper()

	f, err := os.Open(archivePath)
	if err != nil {
		t.Fatalf("Failed to open archive: %v", err)
	}
	defer func() { _ = f.Close() }()

	gz, err := gzip.NewReader(f)
	if err != nil {
		t.Fatalf("Failed to create gzip reader: %v", err)
	}
	defer func() { _ = gz.Close() }()

	tr := tar.NewReader(gz)
	var names []string

	for {
		header, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatalf("Failed to read tar entry: %v", err)
		}
		names = append(names, header.Name)
	}

	return names
}
