package gitlab

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"time"

	gl "gitlab.com/gitlab-org/api/client-go"

	"github.com/valksor/go-mehrhof/internal/storage"
	"github.com/valksor/go-toolkit/pullrequest"
	"github.com/valksor/go-toolkit/workunit"
)

// CreatePullRequest creates a new merge request on GitLab
// This implements the pullrequest.PRCreator interface.
func (p *Provider) CreatePullRequest(ctx context.Context, opts pullrequest.PullRequestOptions) (*pullrequest.PullRequest, error) {
	// Ensure project is configured
	projectPath := p.config.ProjectPath
	if projectPath == "" {
		return nil, ErrProjectNotConfigured
	}

	p.client.SetProjectPath(projectPath)

	// Determine target branch
	targetBranch := opts.TargetBranch
	if targetBranch == "" {
		// Try to get from config
		if p.config.TargetBranch != "" {
			targetBranch = p.config.TargetBranch
		} else {
			// Detect default branch from project
			defaultBranch, err := p.client.GetDefaultBranch(ctx)
			if err != nil {
				return nil, fmt.Errorf("detect default branch: %w", err)
			}
			targetBranch = defaultBranch
		}
	}

	// Use config setting for remove_source_branch if not specified
	removeSourceBranch := p.config.RemoveSourceBranch

	// Create the MR
	mr, err := p.client.CreateMergeRequest(ctx, opts.Title, opts.Body, opts.SourceBranch, targetBranch, removeSourceBranch)
	if err != nil {
		return nil, fmt.Errorf("create merge request: %w", err)
	}

	return &pullrequest.PullRequest{
		ID:     strconv.FormatInt(mr.ID, 10),
		Number: int(mr.IID),
		URL:    mr.WebURL,
		Title:  mr.Title,
		State:  mr.State,
	}, nil
}

// GetDefaultBranch returns the project's default branch.
func (p *Provider) GetDefaultBranch(ctx context.Context) (string, error) {
	if p.config.TargetBranch != "" {
		return p.config.TargetBranch, nil
	}

	return p.client.GetDefaultBranch(ctx)
}

// GenerateMRTitle generates a merge request title from task metadata.
func GenerateMRTitle(taskWork *storage.TaskWork) string {
	if taskWork == nil {
		return "Implementation"
	}

	var title string
	if taskWork.Metadata.ExternalKey != "" {
		title = fmt.Sprintf("[#%s] ", taskWork.Metadata.ExternalKey)
	}

	if taskWork.Metadata.Title != "" {
		title += taskWork.Metadata.Title
	} else {
		title += "Implementation"
	}

	return title
}

// GenerateMRBody generates a merge request body with implementation summary.
func GenerateMRBody(taskWork *storage.TaskWork, specs []*storage.Specification, diffStat string) string {
	var sb strings.Builder

	// Summary section
	sb.WriteString("## Summary\n\n")

	if taskWork != nil && taskWork.Metadata.Title != "" {
		sb.WriteString(fmt.Sprintf("Implementation for: %s\n\n", taskWork.Metadata.Title))
	}

	// Link to issue if this is a GitLab issue task
	if taskWork != nil && taskWork.Source.Type == ProviderName {
		sb.WriteString(fmt.Sprintf("Closes #%s\n\n", taskWork.Metadata.ExternalKey))
	}

	// Specifications section
	if len(specs) > 0 {
		sb.WriteString("## Implementation Details\n\n")
		for _, spec := range specs {
			if spec.Title != "" {
				sb.WriteString(fmt.Sprintf("### %s\n\n", spec.Title))
			}
			// Include first 500 chars of spec content as summary
			content := spec.Content
			if len(content) > 500 {
				content = content[:500] + "..."
			}
			sb.WriteString(content)
			sb.WriteString("\n\n")
		}
	}

	// Changes section
	if diffStat != "" {
		sb.WriteString("## Changes\n\n")
		sb.WriteString("```\n")
		sb.WriteString(diffStat)
		sb.WriteString("\n```\n\n")
	}

	// Test plan section (placeholder)
	sb.WriteString("## Test Plan\n\n")
	sb.WriteString("- [ ] Manual testing\n")
	sb.WriteString("- [ ] Unit tests pass\n")
	sb.WriteString("- [ ] Code review\n\n")

	// Footer
	sb.WriteString("---\n")
	sb.WriteString("*Generated by [Mehrhof](https://github.com/valksor/go-mehrhof)*\n")

	return sb.String()
}

// CreateMRFromTask creates a merge request from task context.
func (p *Provider) CreateMRFromTask(ctx context.Context, taskWork *storage.TaskWork, specs []*storage.Specification, sourceBranch, diffStat string) (*pullrequest.PullRequest, error) {
	title := GenerateMRTitle(taskWork)
	body := GenerateMRBody(taskWork, specs, diffStat)

	opts := pullrequest.PullRequestOptions{
		Title:        title,
		Body:         body,
		SourceBranch: sourceBranch,
		TargetBranch: "", // Will use default
		Draft:        p.config.DraftMR,
	}

	return p.CreatePullRequest(ctx, opts)
}

// ─────────────────────────────────────────────────────────────────────────────
// MR Review Support (PRFetcher, PRCommenter, PRCommentFetcher, PRCommentUpdater)
// ─────────────────────────────────────────────────────────────────────────────

// FetchPullRequest retrieves merge request details.
func (p *Provider) FetchPullRequest(ctx context.Context, number int) (*pullrequest.PullRequest, error) {
	projectPath := p.config.ProjectPath
	if projectPath == "" {
		return nil, ErrProjectNotConfigured
	}

	p.client.SetProjectPath(projectPath)

	iid := int64(number)

	glMR, err := p.client.GetMergeRequest(ctx, iid)
	if err != nil {
		return nil, err
	}

	return &pullrequest.PullRequest{
		ID:         strconv.FormatInt(glMR.ID, 10),
		URL:        glMR.WebURL,
		Title:      glMR.Title,
		State:      glMR.State,
		Number:     int(glMR.IID),
		Body:       glMR.Description,
		HeadSHA:    glMR.SHA,
		HeadBranch: glMR.SourceBranch,
		BaseBranch: glMR.TargetBranch,
		Author:     glMR.Author.Username,
		CreatedAt:  *glMR.CreatedAt,
		UpdatedAt:  *glMR.UpdatedAt,
		Labels:     glMR.Labels,
		Assignees:  extractAssigneesFromMR(glMR.Assignees),
	}, nil
}

// FetchPullRequestDiff retrieves the diff for a merge request.
func (p *Provider) FetchPullRequestDiff(ctx context.Context, number int) (*pullrequest.PullRequestDiff, error) {
	projectPath := p.config.ProjectPath
	if projectPath == "" {
		return nil, ErrProjectNotConfigured
	}

	p.client.SetProjectPath(projectPath)

	iid := int64(number)

	// Get MR details first for branch info
	glMR, err := p.client.GetMergeRequest(ctx, iid)
	if err != nil {
		return nil, err
	}

	// Get diff
	rawDiff, diffs, additions, deletions, err := p.client.GetMergeRequestDiff(ctx, iid)
	if err != nil {
		return nil, err
	}

	// Map files
	providerFiles := make([]pullrequest.FileDiff, len(diffs))
	for i, d := range diffs {
		providerFiles[i] = pullrequest.FileDiff{
			Path:      d.NewPath,
			Mode:      determineMRFileMode(d.NewFile, d.RenamedFile, d.DeletedFile),
			Patch:     getSafeDiff(d),
			Additions: 0, // GitLab API doesn't provide per-file additions
			Deletions: 0, // GitLab API doesn't provide per-file deletions
		}
	}

	return &pullrequest.PullRequestDiff{
		URL:        fmt.Sprintf("%s/-/merge_requests/%d/diffs", glMR.WebURL, number),
		BaseBranch: glMR.TargetBranch,
		HeadBranch: glMR.SourceBranch,
		Files:      providerFiles,
		Patch:      rawDiff,
		Additions:  additions,
		Deletions:  deletions,
		Commits:    0, // GitLab doesn't provide commit count directly in MR
	}, nil
}

// AddPullRequestComment posts a comment to a merge request.
func (p *Provider) AddPullRequestComment(ctx context.Context, number int, body string) (*workunit.Comment, error) {
	projectPath := p.config.ProjectPath
	if projectPath == "" {
		return nil, ErrProjectNotConfigured
	}

	p.client.SetProjectPath(projectPath)

	iid := int64(number)

	glNote, err := p.client.CreateMergeRequestNote(ctx, iid, body)
	if err != nil {
		return nil, err
	}

	return mapMRNoteToComment(glNote), nil
}

// FetchPullRequestComments retrieves all comments on a merge request.
func (p *Provider) FetchPullRequestComments(ctx context.Context, number int) ([]workunit.Comment, error) {
	projectPath := p.config.ProjectPath
	if projectPath == "" {
		return nil, ErrProjectNotConfigured
	}

	p.client.SetProjectPath(projectPath)

	iid := int64(number)

	glNotes, err := p.client.GetMergeRequestNotes(ctx, iid)
	if err != nil {
		return nil, err
	}

	result := make([]workunit.Comment, len(glNotes))
	for i, n := range glNotes {
		result[i] = *mapMRNoteToComment(n)
	}

	return result, nil
}

// UpdatePullRequestComment updates an existing comment on a merge request.
func (p *Provider) UpdatePullRequestComment(ctx context.Context, number int, commentID string, body string) (*workunit.Comment, error) {
	projectPath := p.config.ProjectPath
	if projectPath == "" {
		return nil, ErrProjectNotConfigured
	}

	p.client.SetProjectPath(projectPath)

	iid := int64(number)

	// Parse note ID
	noteID, err := strconv.ParseInt(commentID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid comment ID: %w", err)
	}

	glNote, err := p.client.UpdateMergeRequestNote(ctx, iid, noteID, body)
	if err != nil {
		return nil, err
	}

	return mapMRNoteToComment(glNote), nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper functions for MR review support
// ─────────────────────────────────────────────────────────────────────────────

// extractAssigneesFromMR extracts assignee usernames from MR assignees.
func extractAssigneesFromMR(assignees []*gl.BasicUser) []string {
	if len(assignees) == 0 {
		return nil
	}
	names := make([]string, len(assignees))
	for i, u := range assignees {
		names[i] = u.Username
	}

	return names
}

// determineMRFileMode determines the file mode from GitLab diff flags.
func determineMRFileMode(newFile, renamedFile, deletedFile bool) string {
	if deletedFile {
		return "deleted"
	}
	if renamedFile {
		return "renamed"
	}
	if newFile {
		return "added"
	}

	return "modified"
}

// getSafeDiff extracts the diff string safely.
func getSafeDiff(d *gl.MergeRequestDiff) string {
	if d.Diff == "" {
		return ""
	}

	return d.Diff
}

// mapMRNoteToComment converts a GitLab MR note to a provider Comment.
func mapMRNoteToComment(note *gl.Note) *workunit.Comment {
	author := workunit.Person{
		ID:   strconv.FormatInt(note.Author.ID, 10),
		Name: note.Author.Username,
	}

	if note.Author.Email != "" {
		author.Email = note.Author.Email
	}

	var updatedAt time.Time
	if note.UpdatedAt != nil {
		updatedAt = *note.UpdatedAt
	} else if note.CreatedAt != nil {
		updatedAt = *note.CreatedAt
	}

	return &workunit.Comment{
		ID:        strconv.FormatInt(note.ID, 10),
		Body:      note.Body,
		Author:    author,
		CreatedAt: *note.CreatedAt,
		UpdatedAt: updatedAt,
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// MR Review Submission (PRReviewer interface)
// ─────────────────────────────────────────────────────────────────────────────

// SubmitReview submits a review to a merge request.
// GitLab doesn't have a formal review API like GitHub.
// Instead, we post:
// 1. A summary note with the overall review
// 2. Individual diff notes for per-line comments.
func (p *Provider) SubmitReview(ctx context.Context, opts pullrequest.SubmitReviewOptions) (*pullrequest.ReviewSubmission, error) {
	projectPath := p.config.ProjectPath
	if projectPath == "" {
		return nil, ErrProjectNotConfigured
	}

	p.client.SetProjectPath(projectPath)

	iid := int64(opts.PRNumber)
	commentsPosted := 0

	// Get MR details for the HEAD SHA (needed for diff notes)
	mr, err := p.client.GetMergeRequest(ctx, iid)
	if err != nil {
		return nil, fmt.Errorf("get merge request: %w", err)
	}

	// Post per-line comments as diff notes
	for _, c := range opts.Comments {
		if c.Path != "" && c.Line > 0 {
			// Create discussion on diff
			err := p.client.CreateMergeRequestDiffNote(ctx, iid, mr.DiffRefs.HeadSha, c.Path, c.Line, c.Body)
			if err != nil {
				// Log but continue - some lines may not be in the diff
				continue
			}
			commentsPosted++
		}
	}

	// Build summary note with review verdict
	summaryBody := buildGitLabReviewSummary(opts)

	// Post summary note
	note, err := p.client.CreateMergeRequestNote(ctx, iid, summaryBody)
	if err != nil {
		return nil, fmt.Errorf("create summary note: %w", err)
	}

	return &pullrequest.ReviewSubmission{
		ID:             strconv.FormatInt(note.ID, 10),
		URL:            mr.WebURL + "#note_" + strconv.FormatInt(note.ID, 10),
		CommentsPosted: commentsPosted + 1, // +1 for summary
	}, nil
}

// buildGitLabReviewSummary creates a formatted review summary note.
func buildGitLabReviewSummary(opts pullrequest.SubmitReviewOptions) string {
	var sb strings.Builder

	// Add verdict header
	switch opts.Event {
	case pullrequest.ReviewEventApprove:
		sb.WriteString("### ✅ Mehr Review: Approved\n\n")
	case pullrequest.ReviewEventRequestChanges:
		sb.WriteString("### ⚠️ Mehr Review: Changes Requested\n\n")
	case pullrequest.ReviewEventComment:
		sb.WriteString("### 💬 Mehr Review: Comment\n\n")
	default:
		sb.WriteString("### 📝 Mehr Review\n\n")
	}

	// Add summary
	if opts.Summary != "" {
		sb.WriteString(opts.Summary)
		sb.WriteString("\n\n")
	}

	// Note about inline comments
	if len(opts.Comments) > 0 {
		sb.WriteString(fmt.Sprintf("---\n*%d inline comments posted.*\n", len(opts.Comments)))
	}

	return sb.String()
}
