package gitlab

import (
	"context"
	"fmt"
	"strings"

	"github.com/valksor/go-mehrhof/internal/provider"
	"github.com/valksor/go-mehrhof/internal/storage"
)

// CreatePullRequest creates a new merge request on GitLab
// This implements the provider.PRCreator interface
func (p *Provider) CreatePullRequest(ctx context.Context, opts provider.PullRequestOptions) (*provider.PullRequest, error) {
	// Ensure project is configured
	projectPath := p.config.ProjectPath
	if projectPath == "" {
		return nil, ErrProjectNotConfigured
	}

	p.client.SetProjectPath(projectPath)

	// Determine target branch
	targetBranch := opts.TargetBranch
	if targetBranch == "" {
		// Try to get from config
		if p.config.TargetBranch != "" {
			targetBranch = p.config.TargetBranch
		} else {
			// Detect default branch from project
			defaultBranch, err := p.client.GetDefaultBranch(ctx)
			if err != nil {
				return nil, fmt.Errorf("detect default branch: %w", err)
			}
			targetBranch = defaultBranch
		}
	}

	// Use config setting for remove_source_branch if not specified
	removeSourceBranch := p.config.RemoveSourceBranch

	// Create the MR
	mr, err := p.client.CreateMergeRequest(ctx, opts.Title, opts.Body, opts.SourceBranch, targetBranch, removeSourceBranch)
	if err != nil {
		return nil, fmt.Errorf("create merge request: %w", err)
	}

	return &provider.PullRequest{
		ID:     fmt.Sprintf("%d", mr.ID),
		Number: int(mr.IID),
		URL:    mr.WebURL,
		Title:  mr.Title,
		State:  mr.State,
	}, nil
}

// GetDefaultBranch returns the project's default branch
func (p *Provider) GetDefaultBranch(ctx context.Context) (string, error) {
	if p.config.TargetBranch != "" {
		return p.config.TargetBranch, nil
	}
	return p.client.GetDefaultBranch(ctx)
}

// GenerateMRTitle generates a merge request title from task metadata
func GenerateMRTitle(taskWork *storage.TaskWork) string {
	if taskWork == nil {
		return "Implementation"
	}

	var title string
	if taskWork.Metadata.ExternalKey != "" {
		title = fmt.Sprintf("[#%s] ", taskWork.Metadata.ExternalKey)
	}

	if taskWork.Metadata.Title != "" {
		title += taskWork.Metadata.Title
	} else {
		title += "Implementation"
	}

	return title
}

// GenerateMRBody generates a merge request body with implementation summary
func GenerateMRBody(taskWork *storage.TaskWork, specs []*storage.Specification, diffStat string) string {
	var sb strings.Builder

	// Summary section
	sb.WriteString("## Summary\n\n")

	if taskWork != nil && taskWork.Metadata.Title != "" {
		sb.WriteString(fmt.Sprintf("Implementation for: %s\n\n", taskWork.Metadata.Title))
	}

	// Link to issue if this is a GitLab issue task
	if taskWork != nil && taskWork.Source.Type == ProviderName {
		sb.WriteString(fmt.Sprintf("Closes #%s\n\n", taskWork.Metadata.ExternalKey))
	}

	// Specifications section
	if len(specs) > 0 {
		sb.WriteString("## Implementation Details\n\n")
		for _, spec := range specs {
			if spec.Title != "" {
				sb.WriteString(fmt.Sprintf("### %s\n\n", spec.Title))
			}
			// Include first 500 chars of spec content as summary
			content := spec.Content
			if len(content) > 500 {
				content = content[:500] + "..."
			}
			sb.WriteString(content)
			sb.WriteString("\n\n")
		}
	}

	// Changes section
	if diffStat != "" {
		sb.WriteString("## Changes\n\n")
		sb.WriteString("```\n")
		sb.WriteString(diffStat)
		sb.WriteString("\n```\n\n")
	}

	// Test plan section (placeholder)
	sb.WriteString("## Test Plan\n\n")
	sb.WriteString("- [ ] Manual testing\n")
	sb.WriteString("- [ ] Unit tests pass\n")
	sb.WriteString("- [ ] Code review\n\n")

	// Footer
	sb.WriteString("---\n")
	sb.WriteString("*Generated by [Mehrhof](https://github.com/valksor/go-mehrhof)*\n")

	return sb.String()
}

// CreateMRFromTask creates a merge request from task context
func (p *Provider) CreateMRFromTask(ctx context.Context, taskWork *storage.TaskWork, specs []*storage.Specification, sourceBranch, diffStat string) (*provider.PullRequest, error) {
	title := GenerateMRTitle(taskWork)
	body := GenerateMRBody(taskWork, specs, diffStat)

	opts := provider.PullRequestOptions{
		Title:        title,
		Body:         body,
		SourceBranch: sourceBranch,
		TargetBranch: "", // Will use default
		Draft:        p.config.DraftMR,
	}

	return p.CreatePullRequest(ctx, opts)
}
