package gitlab

import (
	"strings"
	"testing"

	"github.com/valksor/go-mehrhof/internal/storage"
)

func TestGenerateMRTitle(t *testing.T) {
	tests := []struct {
		name     string
		taskWork *storage.TaskWork
		want     string
	}{
		{
			name:     "nil taskWork",
			taskWork: nil,
			want:     "Implementation",
		},
		{
			name: "with title only",
			taskWork: &storage.TaskWork{
				Metadata: storage.WorkMetadata{
					Title: "Add new feature",
				},
			},
			want: "Add new feature",
		},
		{
			name: "with external key and title",
			taskWork: &storage.TaskWork{
				Metadata: storage.WorkMetadata{
					ExternalKey: "123",
					Title:       "Fix login bug",
				},
			},
			want: "[#123] Fix login bug",
		},
		{
			name: "with external key but no title",
			taskWork: &storage.TaskWork{
				Metadata: storage.WorkMetadata{
					ExternalKey: "456",
				},
			},
			want: "[#456] Implementation",
		},
		{
			name: "empty metadata",
			taskWork: &storage.TaskWork{
				Metadata: storage.WorkMetadata{},
			},
			want: "Implementation",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := GenerateMRTitle(tt.taskWork)
			if got != tt.want {
				t.Errorf("GenerateMRTitle() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestGenerateMRBody(t *testing.T) {
	tests := []struct {
		name        string
		taskWork    *storage.TaskWork
		specs       []*storage.Specification
		diffStat    string
		wantContain []string
	}{
		{
			name:     "nil taskWork basic",
			taskWork: nil,
			specs:    nil,
			diffStat: "",
			wantContain: []string{
				"## Summary",
				"## Test Plan",
				"*Generated by [Mehrhof]",
			},
		},
		{
			name: "with gitlab source closes issue",
			taskWork: &storage.TaskWork{
				Metadata: storage.WorkMetadata{
					Title:       "Feature implementation",
					ExternalKey: "42",
				},
				Source: storage.SourceInfo{
					Type: ProviderName,
				},
			},
			specs:    nil,
			diffStat: "",
			wantContain: []string{
				"Implementation for: Feature implementation",
				"Closes #42",
			},
		},
		{
			name:     "with specifications",
			taskWork: nil,
			specs: []*storage.Specification{
				{
					Title:   "Authentication Module",
					Content: "Implement JWT authentication",
				},
			},
			diffStat: "",
			wantContain: []string{
				"## Implementation Details",
				"### Authentication Module",
				"Implement JWT authentication",
			},
		},
		{
			name:     "with diff stat",
			taskWork: nil,
			specs:    nil,
			diffStat: "3 files changed, 100 insertions(+), 20 deletions(-)",
			wantContain: []string{
				"## Changes",
				"```",
				"3 files changed",
			},
		},
		{
			name:     "specification content truncated",
			taskWork: nil,
			specs: []*storage.Specification{
				{
					Title:   "Large Spec",
					Content: string(make([]byte, 600)), // 600 chars - should be truncated
				},
			},
			diffStat: "",
			wantContain: []string{
				"...", // Truncation indicator
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := GenerateMRBody(tt.taskWork, tt.specs, tt.diffStat)

			for _, want := range tt.wantContain {
				if !strings.Contains(got, want) {
					t.Errorf("GenerateMRBody() missing %q\nGot:\n%s", want, got)
				}
			}
		})
	}
}
