package bitbucket

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/valksor/go-mehrhof/internal/provider"
	"github.com/valksor/go-mehrhof/internal/storage"
)

// CreatePullRequest creates a new pull request on Bitbucket.
// This implements the provider.PRCreator interface.
func (p *Provider) CreatePullRequest(ctx context.Context, opts provider.PullRequestOptions) (*provider.PullRequest, error) {
	// Ensure workspace/repo is configured
	workspace := p.config.Workspace
	repoSlug := p.config.RepoSlug

	if workspace == "" || repoSlug == "" {
		return nil, ErrRepoNotConfigured
	}

	p.client.SetWorkspaceRepo(workspace, repoSlug)

	// Determine target branch
	targetBranch := opts.TargetBranch
	if targetBranch == "" {
		if p.config.TargetBranch != "" {
			targetBranch = p.config.TargetBranch
		} else {
			// Detect default branch from repo
			defaultBranch, err := p.client.GetDefaultBranch(ctx)
			if err != nil {
				return nil, fmt.Errorf("detect default branch: %w", err)
			}
			targetBranch = defaultBranch
		}
	}

	// Use config setting for close_source_branch
	closeSourceBranch := p.config.CloseSourceBranch

	// Create the PR
	pr, err := p.client.CreatePullRequest(ctx, opts.Title, opts.Body, opts.SourceBranch, targetBranch, closeSourceBranch)
	if err != nil {
		return nil, fmt.Errorf("create pull request: %w", err)
	}

	webURL := ""
	if pr.Links.HTML != nil {
		webURL = pr.Links.HTML.Href
	}

	return &provider.PullRequest{
		ID:     strconv.Itoa(pr.ID),
		Number: pr.ID,
		URL:    webURL,
		Title:  pr.Title,
		State:  pr.State,
	}, nil
}

// GetDefaultBranch returns the repository's default branch.
func (p *Provider) GetDefaultBranch(ctx context.Context) (string, error) {
	if p.config.TargetBranch != "" {
		return p.config.TargetBranch, nil
	}

	workspace := p.config.Workspace
	repoSlug := p.config.RepoSlug

	if workspace == "" || repoSlug == "" {
		// Don't assume "main" - require explicit configuration
		return "", errors.New("workspace and repo_slug required to detect default branch; set target_branch in config")
	}

	p.client.SetWorkspaceRepo(workspace, repoSlug)

	return p.client.GetDefaultBranch(ctx)
}

// GeneratePRTitle generates a pull request title from task metadata.
func GeneratePRTitle(taskWork *storage.TaskWork) string {
	if taskWork == nil {
		return "Implementation"
	}

	var title string
	if taskWork.Metadata.ExternalKey != "" {
		title = fmt.Sprintf("[#%s] ", taskWork.Metadata.ExternalKey)
	}

	if taskWork.Metadata.Title != "" {
		title += taskWork.Metadata.Title
	} else {
		title += "Implementation"
	}

	return title
}

// GeneratePRBody generates a pull request body with implementation summary.
func GeneratePRBody(taskWork *storage.TaskWork, specs []*storage.Specification, diffStat string) string {
	var sb strings.Builder

	// Summary section
	sb.WriteString("## Summary\n\n")

	if taskWork != nil && taskWork.Metadata.Title != "" {
		sb.WriteString(fmt.Sprintf("Implementation for: %s\n\n", taskWork.Metadata.Title))
	}

	// Link to issue if this is a Bitbucket issue task
	if taskWork != nil && taskWork.Source.Type == ProviderName {
		sb.WriteString(fmt.Sprintf("Closes #%s\n\n", taskWork.Metadata.ExternalKey))
	}

	// Specifications section
	if len(specs) > 0 {
		sb.WriteString("## Implementation Details\n\n")
		for _, spec := range specs {
			if spec.Title != "" {
				sb.WriteString(fmt.Sprintf("### %s\n\n", spec.Title))
			}
			// Include first 500 chars of spec content as summary
			content := spec.Content
			if len(content) > 500 {
				content = content[:500] + "..."
			}
			sb.WriteString(content)
			sb.WriteString("\n\n")
		}
	}

	// Changes section
	if diffStat != "" {
		sb.WriteString("## Changes\n\n")
		sb.WriteString("```\n")
		sb.WriteString(diffStat)
		sb.WriteString("\n```\n\n")
	}

	// Test plan section
	sb.WriteString("## Test Plan\n\n")
	sb.WriteString("- [ ] Manual testing\n")
	sb.WriteString("- [ ] Unit tests pass\n")
	sb.WriteString("- [ ] Code review\n\n")

	// Footer
	sb.WriteString("---\n")
	sb.WriteString("*Generated by [Mehrhof](https://github.com/valksor/go-mehrhof)*\n")

	return sb.String()
}

// CreatePRFromTask creates a pull request from task context.
func (p *Provider) CreatePRFromTask(ctx context.Context, taskWork *storage.TaskWork, specs []*storage.Specification, sourceBranch, diffStat string) (*provider.PullRequest, error) {
	title := GeneratePRTitle(taskWork)
	body := GeneratePRBody(taskWork, specs, diffStat)

	opts := provider.PullRequestOptions{
		Title:        title,
		Body:         body,
		SourceBranch: sourceBranch,
		TargetBranch: "", // Will use default
	}

	return p.CreatePullRequest(ctx, opts)
}

// ─────────────────────────────────────────────────────────────────────────────
// PR Review Support (PRFetcher, PRCommenter, PRCommentFetcher, PRCommentUpdater)
// ─────────────────────────────────────────────────────────────────────────────

// FetchPullRequest retrieves pull request details.
func (p *Provider) FetchPullRequest(ctx context.Context, number int) (*provider.PullRequest, error) {
	workspace := p.config.Workspace
	repoSlug := p.config.RepoSlug

	if workspace == "" || repoSlug == "" {
		return nil, ErrRepoNotConfigured
	}

	p.client.SetWorkspaceRepo(workspace, repoSlug)

	prID := number

	pr, err := p.client.GetPullRequest(ctx, prID)
	if err != nil {
		return nil, err
	}

	webURL := ""
	if pr.Links.HTML != nil {
		webURL = pr.Links.HTML.Href
	}

	author := ""
	if pr.Author != nil {
		author = pr.Author.Username
		if author == "" {
			author = pr.Author.DisplayName
		}
	}

	return &provider.PullRequest{
		ID:         strconv.Itoa(pr.ID),
		URL:        webURL,
		Title:      pr.Title,
		State:      pr.State,
		Number:     pr.ID,
		Body:       pr.Description,
		HeadSHA:    "", // Not available in basic PR type
		HeadBranch: pr.Source.Branch.Name,
		BaseBranch: pr.Destination.Branch.Name,
		Author:     author,
		CreatedAt:  pr.CreatedOn,
		UpdatedAt:  pr.UpdatedOn,
		Labels:     nil, // Bitbucket doesn't have PR labels
		Assignees:  nil, // Would need to fetch reviewers separately
	}, nil
}

// FetchPullRequestDiff retrieves the diff for a pull request.
func (p *Provider) FetchPullRequestDiff(ctx context.Context, number int) (*provider.PullRequestDiff, error) {
	workspace := p.config.Workspace
	repoSlug := p.config.RepoSlug

	if workspace == "" || repoSlug == "" {
		return nil, ErrRepoNotConfigured
	}

	p.client.SetWorkspaceRepo(workspace, repoSlug)

	prID := number

	// Get PR details first for branch info
	pr, err := p.client.GetPullRequest(ctx, prID)
	if err != nil {
		return nil, err
	}

	// Get diff
	rawDiff, diffs, additions, deletions, err := p.client.GetPullRequestDiff(ctx, prID)
	if err != nil {
		return nil, err
	}

	// Map files
	providerFiles := make([]provider.FileDiff, len(diffs))
	for i, d := range diffs {
		providerFiles[i] = provider.FileDiff{
			Path:      d.Path,
			Mode:      d.Mode,
			Patch:     "", // Not parsed from raw diff
			Additions: d.LinesAdded,
			Deletions: d.LinesRemoved,
		}
	}

	return &provider.PullRequestDiff{
		URL:        pr.Links.HTML.Href + "/diff",
		BaseBranch: pr.Destination.Branch.Name,
		HeadBranch: pr.Source.Branch.Name,
		Files:      providerFiles,
		Patch:      rawDiff,
		Additions:  additions,
		Deletions:  deletions,
		Commits:    0, // Not available in basic diff
	}, nil
}

// AddPullRequestComment posts a comment to a pull request.
func (p *Provider) AddPullRequestComment(ctx context.Context, number int, body string) (*provider.Comment, error) {
	workspace := p.config.Workspace
	repoSlug := p.config.RepoSlug

	if workspace == "" || repoSlug == "" {
		return nil, ErrRepoNotConfigured
	}

	p.client.SetWorkspaceRepo(workspace, repoSlug)

	prID := number

	comment, err := p.client.AddPullRequestComment(ctx, prID, body)
	if err != nil {
		return nil, err
	}

	return mapPRCommentToProviderComment(comment), nil
}

// FetchPullRequestComments retrieves all comments on a pull request.
func (p *Provider) FetchPullRequestComments(ctx context.Context, number int) ([]provider.Comment, error) {
	workspace := p.config.Workspace
	repoSlug := p.config.RepoSlug

	if workspace == "" || repoSlug == "" {
		return nil, ErrRepoNotConfigured
	}

	p.client.SetWorkspaceRepo(workspace, repoSlug)

	prID := number

	comments, err := p.client.GetPullRequestComments(ctx, prID)
	if err != nil {
		return nil, err
	}

	result := make([]provider.Comment, len(comments))
	for i, c := range comments {
		result[i] = *mapPRCommentToProviderComment(&c)
	}

	return result, nil
}

// UpdatePullRequestComment updates an existing comment on a pull request.
func (p *Provider) UpdatePullRequestComment(ctx context.Context, number int, commentID string, body string) (*provider.Comment, error) {
	workspace := p.config.Workspace
	repoSlug := p.config.RepoSlug

	if workspace == "" || repoSlug == "" {
		return nil, ErrRepoNotConfigured
	}

	p.client.SetWorkspaceRepo(workspace, repoSlug)

	prID := number

	// Parse comment ID
	id, err := strconv.Atoi(commentID)
	if err != nil {
		return nil, fmt.Errorf("invalid comment ID: %w", err)
	}

	comment, err := p.client.UpdatePullRequestComment(ctx, prID, id, body)
	if err != nil {
		return nil, err
	}

	return mapPRCommentToProviderComment(comment), nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper functions for PR review support
// ─────────────────────────────────────────────────────────────────────────────

// mapPRCommentToProviderComment converts a Bitbucket PR comment to a provider Comment.
func mapPRCommentToProviderComment(c *Comment) *provider.Comment {
	content := ""
	if c.Content != nil {
		content = c.Content.Raw
	}

	author := ""
	if c.User != nil {
		author = c.User.Username
		if author == "" {
			author = c.User.DisplayName
		}
	}

	return &provider.Comment{
		ID:        strconv.Itoa(c.ID),
		Body:      content,
		Author:    provider.Person{ID: author, Name: author},
		CreatedAt: c.CreatedOn,
		UpdatedAt: c.UpdatedOn,
	}
}
