package github

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	gh "github.com/google/go-github/v67/github"

	"github.com/valksor/go-mehrhof/internal/provider"
	"github.com/valksor/go-mehrhof/internal/storage"
)

// CreatePullRequest creates a new pull request on GitHub.
func (p *Provider) CreatePullRequest(ctx context.Context, opts provider.PullRequestOptions) (*provider.PullRequest, error) {
	// Use provider's default owner/repo if not specified in metadata
	owner := p.owner
	repo := p.repo

	if owner == "" || repo == "" {
		return nil, ErrRepoNotConfigured
	}

	p.client.SetOwnerRepo(owner, repo)

	// Determine target branch
	targetBranch := opts.TargetBranch
	if targetBranch == "" {
		// Try to get from config
		if p.config != nil && p.config.TargetBranch != "" {
			targetBranch = p.config.TargetBranch
		} else {
			// Detect default branch from repo
			defaultBranch, err := p.client.GetDefaultBranch(ctx)
			if err != nil {
				return nil, fmt.Errorf("detect default branch: %w", err)
			}
			targetBranch = defaultBranch
		}
	}

	// Determine if draft
	draft := opts.Draft
	if p.config != nil && p.config.DraftPR {
		draft = true
	}

	// Create the PR
	ghPR, err := p.client.CreatePullRequest(ctx, opts.Title, opts.Body, opts.SourceBranch, targetBranch, draft)
	if err != nil {
		return nil, err
	}

	return &provider.PullRequest{
		ID:     strconv.FormatInt(ghPR.GetID(), 10),
		Number: ghPR.GetNumber(),
		URL:    ghPR.GetHTMLURL(),
		Title:  ghPR.GetTitle(),
		State:  ghPR.GetState(),
	}, nil
}

// GeneratePRTitle generates a PR title from task metadata.
func GeneratePRTitle(taskWork *storage.TaskWork) string {
	if taskWork == nil {
		return "Implementation"
	}

	var title string
	if taskWork.Metadata.ExternalKey != "" {
		title = fmt.Sprintf("[#%s] ", taskWork.Metadata.ExternalKey)
	}

	if taskWork.Metadata.Title != "" {
		title += taskWork.Metadata.Title
	} else {
		title += "Implementation"
	}

	return title
}

// GeneratePRBody generates a PR body with implementation summary.
func GeneratePRBody(taskWork *storage.TaskWork, specs []*storage.Specification, diffStat string) string {
	var sb strings.Builder

	// Summary section
	sb.WriteString("## Summary\n\n")

	if taskWork != nil && taskWork.Metadata.Title != "" {
		sb.WriteString(fmt.Sprintf("Implementation for: %s\n\n", taskWork.Metadata.Title))
	}

	// Link to issue if this is a GitHub issue task
	if taskWork != nil && taskWork.Source.Type == "github" {
		sb.WriteString(fmt.Sprintf("Closes #%s\n\n", taskWork.Metadata.ExternalKey))
	}

	// Specifications section
	if len(specs) > 0 {
		sb.WriteString("## Implementation Details\n\n")
		for _, spec := range specs {
			if spec.Title != "" {
				sb.WriteString(fmt.Sprintf("### %s\n\n", spec.Title))
			}
			// Include first 500 chars of spec content as summary
			content := spec.Content
			if len(content) > 500 {
				content = content[:500] + "..."
			}
			sb.WriteString(content)
			sb.WriteString("\n\n")
		}
	}

	// Changes section
	if diffStat != "" {
		sb.WriteString("## Changes\n\n")
		sb.WriteString("```\n")
		sb.WriteString(diffStat)
		sb.WriteString("\n```\n\n")
	}

	// Test plan section (placeholder)
	sb.WriteString("## Test Plan\n\n")
	sb.WriteString("- [ ] Manual testing\n")
	sb.WriteString("- [ ] Unit tests pass\n")
	sb.WriteString("- [ ] Code review\n\n")

	// Footer
	sb.WriteString("---\n")
	sb.WriteString("*Generated by [Mehrhof](https://github.com/valksor/go-mehrhof)*\n")

	return sb.String()
}

// GetDefaultBranch returns the repository's default branch.
func (p *Provider) GetDefaultBranch(ctx context.Context) (string, error) {
	if p.config != nil && p.config.TargetBranch != "" {
		return p.config.TargetBranch, nil
	}

	return p.client.GetDefaultBranch(ctx)
}

// PROptions holds options for PR creation (extends provider.PullRequestOptions).
type PROptions struct {
	provider.PullRequestOptions

	// Additional GitHub-specific options
	MaintainerCanModify bool
	IssueNumber         int // Issue to close when PR is merged
}

// CreatePRFromTask creates a PR from task context.
func (p *Provider) CreatePRFromTask(ctx context.Context, taskWork *storage.TaskWork, specs []*storage.Specification, sourceBranch, diffStat string) (*provider.PullRequest, error) {
	title := GeneratePRTitle(taskWork)
	body := GeneratePRBody(taskWork, specs, diffStat)

	opts := provider.PullRequestOptions{
		Title:        title,
		Body:         body,
		SourceBranch: sourceBranch,
		TargetBranch: "", // Will use default
		Draft:        p.config != nil && p.config.DraftPR,
	}

	// Note: Labels could be added via GitHub API after PR creation if needed

	return p.CreatePullRequest(ctx, opts)
}

// ─────────────────────────────────────────────────────────────────────────────
// PR Review Support (PRFetcher, PRCommenter, PRCommentFetcher, PRCommentUpdater)
// ─────────────────────────────────────────────────────────────────────────────

// FetchPullRequest retrieves pull request details.
func (p *Provider) FetchPullRequest(ctx context.Context, number int) (*provider.PullRequest, error) {
	if p.owner == "" || p.repo == "" {
		return nil, ErrRepoNotConfigured
	}

	p.client.SetOwnerRepo(p.owner, p.repo)

	ghPR, err := p.client.GetPullRequest(ctx, number)
	if err != nil {
		return nil, err
	}

	return &provider.PullRequest{
		ID:         strconv.FormatInt(ghPR.GetID(), 10),
		URL:        ghPR.GetHTMLURL(),
		Title:      ghPR.GetTitle(),
		State:      ghPR.GetState(),
		Number:     ghPR.GetNumber(),
		Body:       ghPR.GetBody(),
		HeadSHA:    ghPR.GetHead().GetSHA(),
		HeadBranch: ghPR.GetHead().GetRef(),
		BaseBranch: ghPR.GetBase().GetRef(),
		Author:     ghPR.GetUser().GetLogin(),
		CreatedAt:  ghPR.GetCreatedAt().Time,
		UpdatedAt:  ghPR.GetUpdatedAt().Time,
		Labels:     extractLabelNamesFromPR(ghPR.Labels),
		Assignees:  extractAssigneesFromPR(ghPR.Assignees),
	}, nil
}

// FetchPullRequestDiff retrieves the diff for a pull request.
func (p *Provider) FetchPullRequestDiff(ctx context.Context, number int) (*provider.PullRequestDiff, error) {
	if p.owner == "" || p.repo == "" {
		return nil, ErrRepoNotConfigured
	}

	p.client.SetOwnerRepo(p.owner, p.repo)

	// Get PR details first for branch info
	ghPR, err := p.client.GetPullRequest(ctx, number)
	if err != nil {
		return nil, err
	}

	// Get diff
	rawDiff, files, additions, deletions, err := p.client.GetPullRequestDiff(ctx, number)
	if err != nil {
		return nil, err
	}

	// Map files
	providerFiles := make([]provider.FileDiff, len(files))
	for i, f := range files {
		providerFiles[i] = provider.FileDiff{
			Path:      f.GetFilename(),
			Mode:      determineFileMode(f.GetStatus()),
			Patch:     f.GetPatch(),
			Additions: f.GetAdditions(),
			Deletions: f.GetDeletions(),
		}
	}

	return &provider.PullRequestDiff{
		URL:        fmt.Sprintf("https://github.com/%s/%s/pull/%d/files", p.owner, p.repo, number),
		BaseBranch: ghPR.GetBase().GetRef(),
		HeadBranch: ghPR.GetHead().GetRef(),
		Files:      providerFiles,
		Patch:      rawDiff,
		Additions:  additions,
		Deletions:  deletions,
		Commits:    ghPR.GetCommits(),
	}, nil
}

// AddPullRequestComment posts a comment to a pull request.
func (p *Provider) AddPullRequestComment(ctx context.Context, number int, body string) (*provider.Comment, error) {
	if p.owner == "" || p.repo == "" {
		return nil, ErrRepoNotConfigured
	}

	p.client.SetOwnerRepo(p.owner, p.repo)

	ghComment, err := p.client.CreatePullRequestComment(ctx, number, body)
	if err != nil {
		return nil, err
	}

	return &provider.Comment{
		ID:        strconv.FormatInt(ghComment.GetID(), 10),
		Body:      ghComment.GetBody(),
		Author:    provider.Person{ID: ghComment.GetUser().GetLogin(), Name: ghComment.GetUser().GetLogin()},
		CreatedAt: ghComment.GetCreatedAt().Time,
		UpdatedAt: ghComment.GetUpdatedAt().Time,
	}, nil
}

// FetchPullRequestComments retrieves all comments on a pull request.
func (p *Provider) FetchPullRequestComments(ctx context.Context, number int) ([]provider.Comment, error) {
	if p.owner == "" || p.repo == "" {
		return nil, ErrRepoNotConfigured
	}

	p.client.SetOwnerRepo(p.owner, p.repo)

	ghComments, err := p.client.GetPullRequestComments(ctx, number)
	if err != nil {
		return nil, err
	}

	result := make([]provider.Comment, len(ghComments))
	for i, c := range ghComments {
		userLogin := c.GetUser().GetLogin()
		result[i] = provider.Comment{
			ID:        strconv.FormatInt(c.GetID(), 10),
			Body:      c.GetBody(),
			Author:    provider.Person{ID: userLogin, Name: userLogin},
			CreatedAt: c.GetCreatedAt().Time,
			UpdatedAt: c.GetUpdatedAt().Time,
		}
	}

	return result, nil
}

// UpdatePullRequestComment updates an existing comment on a pull request.
func (p *Provider) UpdatePullRequestComment(ctx context.Context, number int, commentID string, body string) (*provider.Comment, error) {
	if p.owner == "" || p.repo == "" {
		return nil, ErrRepoNotConfigured
	}

	p.client.SetOwnerRepo(p.owner, p.repo)

	// Parse comment ID
	id, err := strconv.ParseInt(commentID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid comment ID: %w", err)
	}

	ghComment, err := p.client.UpdatePullRequestComment(ctx, number, id, body)
	if err != nil {
		return nil, err
	}

	return &provider.Comment{
		ID:        strconv.FormatInt(ghComment.GetID(), 10),
		Body:      ghComment.GetBody(),
		Author:    provider.Person{ID: ghComment.GetUser().GetLogin(), Name: ghComment.GetUser().GetLogin()},
		CreatedAt: ghComment.GetCreatedAt().Time,
		UpdatedAt: ghComment.GetUpdatedAt().Time,
	}, nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper functions
// ─────────────────────────────────────────────────────────────────────────────

// extractLabelNamesFromPR extracts label names from PR labels.
func extractLabelNamesFromPR(labels []*gh.Label) []string {
	if len(labels) == 0 {
		return nil
	}
	names := make([]string, len(labels))
	for i, label := range labels {
		names[i] = label.GetName()
	}

	return names
}

// extractAssigneesFromPR extracts assignee logins from PR assignees.
func extractAssigneesFromPR(assignees []*gh.User) []string {
	if len(assignees) == 0 {
		return nil
	}
	names := make([]string, len(assignees))
	for i, u := range assignees {
		names[i] = u.GetLogin()
	}

	return names
}

// determineFileMode maps GitHub file status to provider file mode.
func determineFileMode(status string) string {
	switch status {
	case "added":
		return "added"
	case "deleted":
		return "deleted"
	case "renamed":
		return "renamed"
	case "modified":
		return "modified"
	case "changed":
		return "modified"
	default:
		return "modified"
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// PR Review Submission (PRReviewer interface)
// ─────────────────────────────────────────────────────────────────────────────

// SubmitReview submits a formal review to a pull request.
// This creates a GitHub PR review with APPROVED/REQUEST_CHANGES/COMMENT.
func (p *Provider) SubmitReview(ctx context.Context, opts provider.SubmitReviewOptions) (*provider.ReviewSubmission, error) {
	if p.owner == "" || p.repo == "" {
		return nil, ErrRepoNotConfigured
	}

	p.client.SetOwnerRepo(p.owner, p.repo)

	// Map provider event to GitHub event
	var event string
	switch opts.Event {
	case provider.ReviewEventApprove:
		event = "APPROVE"
	case provider.ReviewEventRequestChanges:
		event = "REQUEST_CHANGES"
	case provider.ReviewEventComment:
		event = "COMMENT"
	default:
		event = "COMMENT"
	}

	// Build review comments
	var comments []*gh.DraftReviewComment
	for _, c := range opts.Comments {
		comment := &gh.DraftReviewComment{
			Path: ptr(c.Path),
			Body: ptr(c.Body),
		}

		// Set line number
		if c.Line > 0 {
			comment.Line = ptr(c.Line)
		}

		// Set side if specified
		if c.Side != "" {
			comment.Side = ptr(c.Side)
		}

		// Multi-line comment support
		if c.StartLine > 0 && c.StartLine != c.Line {
			comment.StartLine = ptr(c.StartLine)
		}

		comments = append(comments, comment)
	}

	// Submit review
	review, err := p.client.CreateReview(ctx, opts.PRNumber, event, opts.Summary, comments)
	if err != nil {
		return nil, err
	}

	return &provider.ReviewSubmission{
		ID:             strconv.FormatInt(review.GetID(), 10),
		URL:            review.GetHTMLURL(),
		CommentsPosted: len(comments),
	}, nil
}
