// Package meta defines the tool's identity constants.
// Change Name here to rebrand the entire tool — all derived paths,
// prefixes, and identifiers update automatically.
package meta

import "strings"

// Name is the CLI binary name and the base for all derived identifiers.
const Name = "kvelmo"

// Documentation URL constants.
const (
	DocsBaseNightly = "https://valksor.com/docs/" + Name + "/nightly"
	DocsBaseLatest  = "https://valksor.com/docs/" + Name + "/latest"
)

// Build-time variables set via ldflags.
var (
	Version   = "dev"
	Commit    = "unknown"
	BuildTime = "unknown"
)

// DocsURL returns the documentation URL for the current build.
// Stable releases (v*) link to /latest, all others to /nightly.
func DocsURL() string {
	if strings.HasPrefix(Version, "v") {
		return DocsBaseLatest
	}

	return DocsBaseNightly
}

// OrgDir is the organisation-scoped directory prefix used in both the home
// directory and per-project config directories.
const OrgDir = ".valksor"

var (
	// GlobalDir is the home-relative global config directory: .valksor/kvelmo.
	GlobalDir = OrgDir + "/" + Name

	// ProjectWorkDir is the per-project hidden working directory: .kvelmo
	// Contains specifications, sessions, and worktrees.
	ProjectWorkDir = "." + Name

	// ConfigFile is the settings filename: kvelmo.yaml.
	ConfigFile = Name + ".yaml"

	// EnvPrefix is the environment variable prefix: KVELMO.
	EnvPrefix = strings.ToUpper(Name)

	// BranchPrefix is the git branch name prefix: kvelmo/.
	BranchPrefix = Name + "/"

	// CommitTag is the git commit message tag: [kvelmo].
	CommitTag = "[" + Name + "]"

	// PRTag is the pull request generated-by footer.
	PRTag = "*Generated by [" + Name + "]*"

	// UserAgent is the HTTP user-agent string for model downloads.
	UserAgent = Name + "-model-downloader/1.0"
)
